name: Sample Action with Email Step

on:
  workflow_dispatch:  # allows manual trigger from GitHub UI

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 22f3001796@ds.study.iitm.ac.in
        run: echo "Hello, world!"
